### ISSUE TITLE
9장 리액트 라우터 Youtube 컴포넌트 작동안되는 이슈

### ISSUE THREAD

**Issue by hash1018** [stepanowon/react-ts-quickstart#1]
안녕하세요.

덕분에 책으로 타입스크립트랑 리액트 열공 중입니다. ㅎㅎ

다름이 아니라 9장 학습하다가 중첩 라우터 부분에서 유튜브 플레이어가 재생이 안되는 이슈가 있어서 질문드려요.

<img width="1792" alt="Screen Shot 2023-01-01 at 11 40 48 AM" src="https://user-images.githubusercontent.com/46293206/210159579-83971d66-1533-4bd4-8620-7b1cac01eeb5.png">

에러메세지는 위와 같이 뜹니다. 혹시 해결방법을 아신다면 답글 부탁드려요.

**Comment by hash1018** [comment]
Chrome 에선 되네요. Safari에선 안되고..

**Comment by stepanowon** [comment]
safari는 테스트를 해보지 못했네요. chrome, firefox까지는 잘 실행되는 것을 확인했습니다 
아미지 react-youtube 컴포넌트 라이브러리의 문제로 보여집니다. 

![image](https://user-images.githubusercontent.com/1870088/210189493-11b6a843-c104-44e5-bf37-bb95311d7698.png)

**Comment by stepanowon** [comment]
첨부 파일의 예제를 다시 한번 돌려보시기 바랍니다.
[router-test-app-99.zip](https://github.com/stepanowon/react-ts-quickstart/files/10329788/router-test-app-99.zip)

**Comment by stepanowon** [comment]
일단은 사파리 에뮬레이터 상에서는 잘  작동하는 것을 확인했습니다. 내일 맥북으로 테스트하고 다시 말씀드릴께요.
혹시 시간이 되시면 다음 URL에서 테스트한번더 해보시겠습니까?

https://router-test-app.vercel.app

**Comment by stepanowon** [comment]
일단 제 맥북 사파리 브라우저에서는 잘 작동하는 것을 확인하였습니다.
<img width="1106" alt="스크린샷 2023-01-02 오후 12 53 52" src="https://user-images.githubusercontent.com/1870088/210194074-02a5c7fd-4f90-4a73-874f-a385dc493c43.png">

**Comment by hash1018** [comment]
> 일단은 사파리 에뮬레이터 상에서는 잘 작동하는 것을 확인했습니다. 내일 맥북으로 테스트하고 다시 말씀드릴께요. 혹시 시간이 되시면 다음 URL에서 테스트한번더 해보시겠습니까?
> 
> https://router-test-app.vercel.app

네 여기서 들어가서 확인 해보니 되네요.
<img width="1792" alt="Screen Shot 2023-01-02 at 10 06 18 PM" src="https://user-images.githubusercontent.com/46293206/210235512-1877bdf7-d2ff-4380-b0e3-0bc63717ca99.png">

**Comment by hash1018** [comment]
선생님 레포지토리 클론해서 09폴더-52폴더에 들어가서 소스 그대로 해봐도 똑같이 뜨네용. 제 피씨가 문제인거 같은데.. 해결방법을 모르겠군요 ㅎㅎ.

<img width="1792" alt="Screen Shot 2023-01-02 at 10 18 06 PM" src="https://user-images.githubusercontent.com/46293206/210236989-b9c8945d-765c-46ab-8529-db4803363e1f.png">

**Comment by stepanowon** [comment]
네...그건 저도 해결책을 모르겠네요.
혹시나 해서 최신 맥북 m2 기반에서도 사파리 브라우저로 실행해보았습니다만 정상이었습니다.

<img width="1212" alt="스크린샷 2023-01-04 오전 8 41 08" src="https://user-images.githubusercontent.com/1870088/210459513-f0acff93-14cc-4c05-9be6-b598036af2f4.png">
