### ISSUE TITLE
해당 지점에서 에러가 발생합니다 

### ISSUE THREAD

**Issue by likeyellow** [stepanowon/react-ts-quickstart#2]
https://github.com/stepanowon/react-ts-quickstart/blob/0cacf51555b3ded9e5d35ae2fe72d0dd2e3dd513/ch10/todolist-app-router/src/pages/EditTodo.tsx#L16C6-L16C6

[  에러 내용 ]
React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?  react-hooks/rules-of-hooks

useState 훅을 쓸때 if문같은 조건절 뒤에 쓰면 안 된다고 하는것 같습니다 ㅠㅠ

**Comment by stepanowon** [comment]
혹시 useState() 문을 if 문 안에서 사용한 것은 아닌지요?
혹시나해서 저도 다시 테스트해보았는데 문제가 없습니다.
